# Generated by Django 3.2.11 on 2023-08-25 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='directory_counterparties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование контракта')),
            ],
        ),
        migrations.CreateModel(
            name='directory_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование товара')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='document_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_document', models.IntegerField(blank=True, null=True, verbose_name='Номер документа')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('summ_document', models.IntegerField(null=True, verbose_name='Сумма документа')),
                ('link_dc', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_dev.directory_counterparties')),
            ],
        ),
        migrations.CreateModel(
            name='product_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_fact', models.IntegerField(blank=True, null=True, verbose_name='Количество фактическое')),
                ('count_reserv', models.IntegerField(blank=True, null=True, verbose_name='Количество в резерве')),
                ('link_dp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_dev.directory_product')),
            ],
        ),
        migrations.CreateModel(
            name='document_specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('counts_reserv', models.IntegerField(blank=True, null=True, verbose_name='Количество в резерве')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Скидка')),
                ('link_dh', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_dev.document_header')),
                ('link_dp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_dev.directory_product')),
            ],
        ),
    ]
