# Generated by Django 3.2.11 on 2023-08-27 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_dev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_specification',
            name='link_ps',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_dev.product_stock'),
        ),
    ]
