# Generated by Django 3.2.11 on 2023-08-28 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_dev', '0002_document_specification_link_ps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_specification',
            name='link_dh',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_dev.document_header'),
        ),
        migrations.AlterField(
            model_name='document_specification',
            name='link_dp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_dev.directory_product'),
        ),
        migrations.AlterField(
            model_name='document_specification',
            name='link_ps',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_dev.product_stock'),
        ),
    ]
