# Generated by Django 3.2.11 on 2023-08-28 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_dev', '0003_auto_20230828_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_header',
            name='link_dc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_dev.directory_counterparties'),
        ),
        migrations.AlterField(
            model_name='product_stock',
            name='link_dp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_dev.directory_product'),
        ),
    ]
