# Generated by Django 3.2.11 on 2023-08-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_dev', '0004_auto_20230828_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory_product',
            name='price',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Цена'),
        ),
    ]
